### ISSUE TITLE
[Bug]: Can't activate Cloud Storage even with paid MineTogether account

### ISSUE THREAD

**Issue by MrUnhandy** [FTBTeam/FTB-App#611] opened 2022-06-15 14:16 UTC
### What Operating System

Windows 10

### App Version

1.3.0

### UI Version

2e021f8e74

### Debug Code

FTB-DBGSEDIBACONE

### Describe the bug

I can't activate cloud storage, even though I have a paid MineTogether account

### Steps to reproduce

1. Go to settings of a modpack
2. Scroll down to Cloud save uploads
3. See that it is greyed out

### Expected behaviour

That I am able to activate the slider next to the Cloud Save option.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment] 2022-07-24 15:01
Duplicate of #465 

We're working on fixing this atm

**Closed by MichaelHillcox** 2022-07-24 15:01 UTC
Labels: bug
