### ISSUE TITLE
[Bug] Closing overwolf before the FTB app leaves a java.exe process running.

### ISSUE THREAD

**Issue by gozulio** [FTBTeam/FTB-App#352] opened 2020-11-28 19:29 UTC
**Operating System:**
OS: Windows 10

**App Version:**
202011272035-6c3f7406fc-prototyping

**UI Version:**
b78fcbfa

**Log Files:**
https://pste.ch/sulupivoso

**Describe the bug**
When the application is terminated by overwolf, it leaves behind a java.exe process from openjdk11.

**To Reproduce**
1.) Open the FTB app.
2.) Go to the system tray and right click overwolf, and click "Exit Overwolf".
3.) Open task manager. The errant process will show up under Background Processes either under overwolf with a console process or just on it's own..

**Expected behaviour**
When you close the FTB app first, then overwolf, the process doesn't get left behind. I would expect this to be the case when closing overwolf before the launcher.

**Screenshots**
this java process was not there before opening the program.
![image](https://user-images.githubusercontent.com/10771387/100524307-00dfa400-3185-11eb-96e0-cf6999d117c8.png)

**Comment by Gaz492** [comment] 2021-01-11 22:20
I believe this issue has been resolved in newer versions of the app. If the issue is still present could you open a new issue?

**Closed by Gaz492** 2021-01-11 22:20 UTC
