### ISSUE TITLE
[Bug]Unable to install the App laucher

### ISSUE THREAD

**Issue by aliceinwonderpants** [FTBTeam/FTB-App#158] opened 2020-06-03 20:37 UTC
**Operating System:**
OS:Windows 8.1

**Installer Version:**
Installer:FTBA_windows-x64_1_0_8.exe

**App Version:**
App: 1.0.8

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app
[INFO] logger started at Wed Jun 03 11:40:36 EDT 2020
[INFO] executable name: C:\Users\Antoine\AppData\Roaming\FTBA\FTBApp.exe
[INFO] install4j version: 8.0.5 (build 8155)
[INFO] Properties: 
-- listing properties --
sun.desktop=windows
awt.toolkit=sun.awt.windows.WToolkit
jdk.extensions.version=11.0.5.0
file.encoding.pkg=sun.io
java.specification.version=11
install4j.launcherId=69
sun.jnu.encoding=MS932
java.class.path=C:\Users\Antoine\AppData\Roaming\FTBA...
sun.awt.enableExtraMouseButtons=true
java.vm.vendor=Eclipse OpenJ9
sun.arch.data.model=64
com.ibm.vm.bitmode=64
install4j.exeDir=C:\Users\Antoine\AppData\Roaming\FTBA\
user.variant=
com.ibm.oti.vm.library.version=29
java.vendor.url=http://www.eclipse.org/openj9
user.timezone=America/New_York
java.vm.specification.version=11
os.name=Windows 8.1
user.country=CA
sun.boot.library.path=c:\users\antoine\appdata\roaming\ftba...
sun.java.command=C:\Users\Antoine\AppData\Roaming\FTBA...
sun.cpu.endian=little
exe4j.unextractedPosition=0
user.home=C:\Users\Antoine
user.language=en
java.specification.vendor=Oracle Corporation
java.version.date=2019-10-15
java.home=c:\users\antoine\appdata\roaming\ftba...
ibm.signalhandling.rs=false
jdk.extensions.name=Extensions for OpenJDK for Eclipse Op...
file.separator=\
line.separator=

java.specification.name=Java Platform API Specification
java.vm.specification.vendor=Oracle Corporation
java.compiler=j9jit29
com.ibm.util.extralibs.properties=
exe4j.moduleName=C:\Users\Antoine\AppData\Roaming\FTBA...
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
com.ibm.oti.configuration=scar
exe4j.tempDir=
java.awt.fonts=
com.ibm.oti.shared.enabled=false
com.ibm.oti.vm.bootstrap.library.path=c:\users\antoine\appdata\roaming\ftba...
exe4j.consoleCodepage=cp0
com.ibm.cpu.endian=little
java.fullversion=11.0.5+10
JRE 11 Windows 8.1 amd64-64...
exe4j.isInstall4j=true
java.runtime.version=11.0.5+10
user.name=Antoine
path.separator=;
os.version=6.3
java.runtime.name=OpenJDK Runtime Environment
ibm.signalhandling.sigint=true
file.encoding=Cp1252
java.vm.name=Eclipse OpenJ9 VM
java.vendor.version=AdoptOpenJDK
exe4j.semaphoreName=Local\c:_users_antoine_appdata_roamin...
ibm.signalhandling.sigchain=true
install4j.appDir=C:\Users\Antoine\AppData\Roaming\FTBA\
java.io.tmpdir=C:\Users\Antoine\AppData\Local\Temp\
java.version=11.0.5
user.dir=C:\Users\Antoine\AppData\Roaming\FTBA
com.ibm.system.agent.path=c:\users\antoine\appdata\roaming\ftba...
os.arch=amd64
java.vm.specification.name=Java Virtual Machine Specification
java.awt.printerjob=sun.awt.windows.WPrinterJob
os.encoding=UTF8
java.library.path=c:\users\antoine\appdata\roaming\ftba...
java.vm.info=JRE 11 Windows 8.1 amd64-64-Bit 20191...
java.vendor=Eclipse OpenJ9
java.vm.version=openj9-0.17.0
ibm.system.encoding=MS932
com.ibm.jcl.checkClassPath=
sun.io.unicode.encoding=UnicodeLittle
apple.awt.UIElement=true
java.class.version=55.0
exe4j.launchName=C:\Users\Antoine\AppData\Roaming\FTBA...
install4j.swt=false
[INFO] Variable changed: sys.resolveUserSpecificInstallationDir=false[class java.lang.String]
[INFO] com.install4j.runtime.beans.actions.control.RunScriptAction [ID 348]: Execute action
       Property rollbackScript: null
       Property script: com.install4j.script.I4jScript_Internal_83
       Property rollbackSupported: false
       Execute action successful after 5 ms
[INFO] com.install4j.runtime.beans.actions.update.CheckForUpdateAction [ID 349]: Execute action
       Property connectTimeout: 10000
       Property connectionFailureScript: null
       Property readTimeout: 20000
       Property requestHeaders: []
       Property url: https://apps.modpacks.ch/FTBApp/release.xml
       Property variable: updateDescriptor
       Property acceptAllCertificates: false
       Property askForProxy: true
       Property rollbackSupported: false
       Property showError: true
       Download: https://apps.modpacks.ch/FTBApp/release.xml to C:\Users\Antoine\AppData\Local\Temp\i4jupd13363298384178379759.xml; size: -1 bytes
       Variable changed: updateDescriptor=com.install4j.runtime.installer.config.update.UpdateDescriptorImpl@c18d332[class com.install4j.runtime.installer.config.update.UpdateDescriptorImpl]
       Execute action successful after 1064 ms
[INFO] com.install4j.runtime.beans.actions.control.SetVariableAction [ID 350]: Execute action
       Property script: com.install4j.script.I4jScript_Internal_84
       Property variableName: updateDescriptorEntry
       Property failIfNull: true
       Property onlyIfUndefined: false
       Property responseFileVariable: false
       Property rollbackSupported: false
[ERROR] com.install4j.runtime.beans.actions.control.SetVariableAction [ID 350]: Execute action not successful after 1 ms
[INFO] Canceled

**Describe the bug**
I am unable to install the app. The installer freezes at "preparing the install4j" then I get the "Java(TM) VM could not be started" error
**To Reproduce**
Steps to reproduce the behaviour:
1. Launch installer (as admin or otherwise)
2. Wait 
3. Freezes at "Preparing the install4j"

**Expected behaviour**
I just want the launcher to install

**Comment by Cloudhunter** [comment] 2020-06-12 12:33
Duplicate of #77

**Closed by Cloudhunter** 2020-06-12 12:33 UTC
