### ISSUE TITLE
[Bug]: Difficulty finding mods using "Add more mods" button

### ISSUE THREAD

**Issue by BubbaVB** [FTBTeam/FTB-App#635] opened 2022-07-14 12:48 UTC
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Debug Code

                                               ███████ ████████ ██████                                                ██         ██    ██   ██                                                █████      ██    ██████                                                ██         ██    ██   ██                                                ██         ██    ██████                                                   Version: 1.0.1-576c95d2                                              Thu, 14 Jul 2022 12:32:56 UTC   # System Information   INFO  OS: Microsoft Windows 10 Home (10.0.19043)  INFO  CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (GenuineIntel)  INFO  Memory: 5.59 GiB / 15.88 GiB (35.00% used)  # FTB App Checks   SUCCESS  FTB App directory (AppData): file/directory exists  ## Validating App structure   SUCCESS  Minecraft bin directory: file/directory exists  ## App info   INFO  Located app at C:\Users\Shannon\AppData\Local/.ftba  INFO  App version: 1.22.608.1143  INFO  Backend version: 202206081143-2e021f8e74-release  INFO  Web version: 2e021f8e74  INFO  Branch: release  SUCCESS  Does app_settings.json exist?: file/directory exists  INFO  Instance Location:  C:\Users\Shannon\AppData\Local\.ftba\instances  # Check for instances   SUCCESS  instances directory: file/directory exists  INFO  found instance:  6473ea8b-24a6-4c07-90e0-1d53a50108d0  INFO  Name: FTB Presents Direwolf20 1.18  INFO  Version: 1.7.0  INFO  Version ID: 2233  INFO  Memory: 6144  INFO  Min/Rec Memory: 4096/6144  INFO  Custom Args:  INFO  Embedded JRE: true  INFO  Is Modified: true  SUCCESS  6473ea8b-24a6-4c07-90e0-1d53a50108d0 logs folder: file/directory exists  INFO  Latest log timestamp: 2022-07-13 16:13:02  SUCCESS  Uploaded 6473ea8b-24a6-4c07-90e0-1d53a50108d0/logs/latest.log: https://pste.ch/asiloyoled  SUCCESS  6473ea8b-24a6-4c07-90e0-1d53a50108d0 instance.json: file/directory exists  SUCCESS  6473ea8b-24a6-4c07-90e0-1d53a50108d0 instance.json: json is valid  # Upload logs   SUCCESS  Uploaded bin/settings.json: https://pste.ch/rujocavixo  SUCCESS  Uploaded bin/launcher_log.txt: https://pste.ch/ucekidutik  SUCCESS  Uploaded bin/launcher_cef_log.txt: https://pste.ch/cakaboxodo  SUCCESS  Uploaded logs/latest.log: https://pste.ch/fopuvelura  SUCCESS  Uploaded logs/debug.log: https://pste.ch/mogakacohe  SUCCESS  Overwolf Logs: file/directory exists  SUCCESS  Uploaded Overwolf/Log/Apps/FTB App/index.html.log: https://pste.ch/onomoseyoh  SUCCESS  Uploaded Overwolf/Log/Apps/FTB App/background.html.log: https://pste.ch/cuhifezeda  WARNING  Uploading Overwolf/Log/Apps/FTB App/chat.html.log: failed to open file  # Debug Report Completed  Please provide this code to support: FTB-DBGIKASUNUMET   INFO  Press ESC to exit...

### Describe the bug

Most searches result in 0 results

### Steps to reproduce

1.  Click on Add more mods
2. Search for a mod

### Expected behaviour

Find mods when searching

### Additional information

I have a very difficult time finding mods when I click on the "Add more mods" button.  This happens even when I know the exact name of the mod.  For example I was looking for Just Enough Resources (JER).  No matter what I type for the name it results in 0 results.  

Other examples:
Looking for FTB Utilimine.  The only way I found it was I searched for FTB.
Looking for Dimensional Storage (Mod Name:  DimStorage) returns 0 results no matter the search combination.
Looking for Advanced Generators (Mod Name is the same) returns 0 results no matter the search combination.

This feature needs to be updated to be more user friendly.  As an example look at how mods are found on the CurseForge launcher.  Ultimately I have resorted to using Google to search for CurseForge "Mod Name" to find, download, & install mods manually because it's easier.

### Information

- [X] I have provided as much information as possible

**Comment by AwsetWraeCZE** [comment] 2022-07-23 09:31
I have the same problem

**Comment by MichaelHillcox** [comment] 2022-07-24 15:40
Fixed in dev,

Duplicate of #621

**Closed by MichaelHillcox** 2022-07-24 15:40 UTC
Labels: bug
