### ISSUE TITLE
Can not install Mod packs

### ISSUE THREAD

**Issue by Target204** [FTBTeam/FTB-App#617] opened 2022-06-20 23:41 UTC
### What Operating System

Windows 10

### App Version

1.3.0   202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Debug Code

FTB-DBGPOLIQEBIVO

### Describe the bug

download any pack and get Fatal Exceptions preparing installation task

### Steps to reproduce

Run Launcher

### Expected behaviour

Make Launcher work

### Screenshots

![image](https://user-images.githubusercontent.com/82024388/174689278-fa90c941-7c82-4426-a4d0-9faeadcfeb7e.png)

### Additional information

I have had this problem since installing your launcher.

### Information

- [X] I have provided as much information as possible

**Comment by JenevieveShe** [comment] 2022-06-22 05:10
I encountered the same issue yesterday. I ran the debug exe and got the code FTB-DBGHENEDOJOPA

**Comment by FreeHighFi** [comment] 2022-07-22 20:06
I have the same Problem.

**Comment by MichaelHillcox** [comment] 2022-07-24 15:20
@JenevieveShe your issue must have been when our api was down, this should be fixed now

@FreeHighFi please open a new issue with your own debug tool

For the original issue, duplicate of #479

**Closed by MichaelHillcox** 2022-07-24 15:21 UTC
Labels: bug
