### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by faedemon** [FTBTeam/FTB-App#348] opened 2020-11-23 18:23 UTC
**Operating System:**
OS:10.15.5

**Installer Version:**
Installer:202007161516-479dedc615-release

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs
https://pste.ch/cozekinino
**Describe the bug**
When I click on the home tab, discover tab, or browse tab no mod packs are displayed. There is nothing I can see or click on except for the previous and next buttons on the discover tab
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to home, discover, or browse tab
2. Click on nothing
3. Scroll down to nothing

**Expected behaviour**
I expected to be available mod packs showing up for me to view.

**Screenshots**
![Screen Shot 2020-11-23 at 1 22 29 PM](https://user-images.githubusercontent.com/74927348/100000051-0c029080-2d8f-11eb-9d32-df6f96ad5054.png)
![Screen Shot 2020-11-23 at 1 22 18 PM](https://user-images.githubusercontent.com/74927348/100000060-0f961780-2d8f-11eb-9751-546335063bca.png)
![Screen Shot 2020-11-23 at 1 22 07 PM](https://user-images.githubusercontent.com/74927348/100000069-12910800-2d8f-11eb-87d7-1fe32b7fe1ff.png)
![Screen Shot 2020-11-23 at 1 49 32 PM](https://user-images.githubusercontent.com/74927348/100002564-c0ea7c80-2d92-11eb-8faf-8a102319472d.png)

**Additional context**
New Problem! I closed and then re-opened the app and now it is stuck on the loading screen saying "please wait"
I can get back into the app now, I deleted and re-downloaded the app and I can open it now, but the mod problem is still there.
Edit 3: I can, and cannot get into the app. If I click on the icon in finder that say "FTB" it will open the app, but if I try to open the app via the icon the looks like a model of an atom it repeats the "please wait" screen and doesn't load.

**Comment by TheWarGamer11** [comment] 2020-11-23 23:54
from what I saw from your hastebin it looks like this failed to load on line 22
>Failed to load class "org.slf4j.impl.StaticLoggerBinder"

From what I gathered from my own hastebin https://pste.ch/amelupuyan that this stand alone app might be missing a implantation of a logging framework.

I do get the never ending loading screen, and I get around this by closing the program on the "please wait..." screen and restarting the app and it loads up quickly after.

I may be wrong in my assumptions, as I don't know how to code, however I'm good at searching the web based on the error log to see if anyone else has come across this problem and how they fixed it.

![concrete-bindings](https://user-images.githubusercontent.com/74845174/100028423-8bef2180-2db4-11eb-85e5-66d3a37b1a77.png)
Image is pulled from http://slf4j.org/manual.html

Which brought me to this nice video, which if the problem is missing a implantation of a logging framework. Then choosing the right logging framework should fix the problem as this app appears to be a stand alone app.

https://www.youtube.com/watch?v=cASgti1L9rw&feature=emb_logo

**Comment by faedemon** [comment] 2020-11-24 01:25
@TheWarGamer11 I thank you for your comment, but I am afraid this doesn't really assist me in resolving the issue. I myself am not a coder, I simply wish to run and use this app. While I have understood from the video that my app is somehow missing a "framework" I am not sure how to implement it. If I could get some assistance, or if you could point me to someone who could give me assistance that would be greatly appreciated.

**Comment by TheWarGamer11** [comment] 2020-11-24 23:28
@faedemon I was hoping that when the one of the devs take a look at this report, that my message could help them with the problem that I have seen on a few recent bug reports via there hastebin reports, Many of them seem to be having this org.slf4j.impl.StaticLoggerBinder error.

If this org.slf4j.impl.StaticLoggerBinder is missing a frame work, then once it is implemented, it could be pushed out to all clients fixing one more errors, but could also cause some kind of unforeseen error, which is why I have faith in the devs and the work they have done now and in the past.

I myself have overlooked things in the past, and any refresher/ideas that could help I find is always helpful. Who knows, maybe creeperhost has changed something on there end that is throwing out errors. I do hope if that is the case, the devs and the hosting platform for the launcher can work this error out. This could be a simple problem, or a very complex one that would require more than average time to solve.

At face value (according to hastebins) it seems to be a missing framework, but there can be more to it, there could be a reason why there is no frame work. I'm sure the dev are aware of the problem or I hope they are as the read through the errors hastebins here on github.

You might be able to get a "quick fix" from the Discord server, Feed The Beast under the community channels # ftb-app.
otherwise best thing to do is wait for the devs to look into this.

**Comment by Gaz492** [comment] 2021-01-11 23:46
Do you still have the issue on newer versions of the app?
If you do would you be able to open a new issue and follow the bug report template for your operating system?

**Closed by Gaz492** 2021-01-11 23:46 UTC
