### ISSUE TITLE
[Bug]: some content is missing

### ISSUE THREAD

**Issue by oDaicuNexusAD** [FTBTeam/FTB-App#775] opened 2022-11-30 15:51 UTC
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Log Files

so. today i wanted to play some sevtech ages and the modpack vanished from the ftb app and if i search the modpack name i can find it but i can't download it and if i try it doesn't shows me any versions and i dont know what to do. i don't want to lose my progress.

### Debug Code

FTB-DBGRUVIXAXITE

### Describe the bug

my modpack dissapeared

### Steps to reproduce

honestly i don't know what to write here

### Expected behaviour

i want the mod pack to be again on the app and work fine

### Information

- [X] I have provided as much information as possible

**Comment by CoryNB** [comment] 2022-12-27 02:39
could be version updates or even some things breaking forcing removal.

**Comment by MichaelHillcox** [comment] 2023-06-22 21:41
Caused by instance corruption. I'm gunna close this but please @ me in discord if you still have the broken instance and would like it fixed. I'm in the FTB Discord https://go.ftb.team/discord and @righthuggingnow

**Closed by MichaelHillcox** 2023-06-22 21:41 UTC
Labels: bug
