### ISSUE TITLE
[BUG] Error! Profile validation failed, please login again.

### ISSUE THREAD

**Issue by Radon8472** [FTBTeam/FTB-App#881] opened 2023-04-01 06:23 UTC
### What Operating System

Windows 7

### Debug Code

FTB-DBGKOTOPIQEGU

### Describe the bug

I try to launch the modpack and get message "Profile validation failed, please login again."

### Steps to reproduce

1. open launcher
2. Got to "Home"
3. Choose your Modpack
4. Click to "Play"

### Expected behaviour

Mod pack should be started

### Screenshots

With existing validated Account:
![Screenshot_017](https://user-images.githubusercontent.com/30496382/229269218-2e7e44fd-1c63-476b-a64a-a812fd6eb0f6.jpg)

After Re-Adding Account:
![Screenshot_020](https://user-images.githubusercontent.com/30496382/229269572-00026d6b-0996-47bf-a4d9-e03a261ae204.jpg)

### Additional information

- my issue seems to be the same like #709.
- [x] Login my account in vanilla minecraft works fine
- [x] Re-Adding account does not work, resulting in a Error 503 from your servers (see screenshot)
- [x]  Restarting FTP does not work
- The Debug-Tool complains it cannot upload " chat.html.log"
- The debugtools is using Linux color code for windows-console what makes it very hard to read.

See this:
```
                           [36m[36m███████ [0m[0m[32m[32m████████ [0m[0m[31m[31m██████  [0m[0m
                           [36m[36m██      [0m[0m[32m[32m   ██    [0m[0m[31m[31m██   ██ [0m[0m
                           [36m[36m█████   [0m[0m[32m[32m   ██    [0m[0m[31m[31m██████  [0m[0m
                           [36m[36m██      [0m[0m[32m[32m   ██    [0m[0m[31m[31m██   ██ [0m[0m
                           [36m[36m██      [0m[0m[32m[32m   ██    [0m[0m[31m[31m██████  [0m[0m
                           
                           
                            Version: 1.0.1-e79a6679
                         Sat, 01 Apr 2023 06:18:19 UTC
                                        
............
[1;33m[0m[0m
[1m[1mPlease provide this code to support: FTB-DBGTOHODESOVO[0m
[1m[0m[0m
[30;46m[30;46m INFO [0m[0m [96m[96mPress ESC to exit...[0m[0m

```

**Comment by Radon8472** [comment] 2023-04-01 07:13
I spend some more invstigations and found https://status.feed-the-beast.com/
I think the reason for this issue could be, that `msauth.feed-the-beast.com` is currently down.

![Screenshot_021](https://user-images.githubusercontent.com/30496382/229271450-ba666500-000d-4f42-8790-530502f71d4c.jpg)

**Comment by PoxyDoxy** [comment] 2023-04-01 07:31
Looks like Creeperhost (185.210.136.232) is down, it's also effecting the Discord link too.

Confirmed by bypassing cloudflare direct to server which matches the current webpage results.
```
root@sapphire:~# curl --connect-to 185.210.136.232 https://msauth.feed-the-beast.com/
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
root@sapphire:~# curl --connect-to 185.210.136.232 https://go.ftb.team/discord
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by knoffelstokkie** [comment] 2023-04-01 08:07
Having the same issue. Anything we can do?

**Comment by Officialy** [comment] 2023-04-01 08:22
All has been fixed now, thanks for tracking this guys! <3

**Closed** 2023-04-01 08:22 UTC
Labels: bug
