### ISSUE TITLE
[Bug] Can't install Modpack Sevtech: Ages

### ISSUE THREAD

**Issue by GEWDA** [FTBTeam/FTB-App#601] opened 2022-06-10 11:31 UTC
Whenever I try to install the Curseforge modpack **Sevtech: Ages**, it displays an error message like shown:

![image](https://user-images.githubusercontent.com/26444370/173054028-6931ad03-5850-4b0f-826e-b58b9a3cb8a1.png)

I have tried changing the instance location, but this did not work. I have tried installing a different Curseforge pack, and that one did work. I have tried installing a different pack by the same author, and that also did not work.

Here are the logs after a few attempts, then changing the instance folder location, followed by another attempt, then trying a different modpack install (which worked), then nuking the instances folder and re-downloading the desired pack (which failed), then attempting a different pack by the same author (which also failed), and then re-downloading a different pack (which worked):

[https://pste.ch/xojofuyetu](url)

App Version:
202205171618-14abefffbf-release

UI Version:
14abefffbf

Debug Code (different day with same issue):
FTB-DBGIRASETAMOQ

**Comment by MichaelHillcox** [comment] 2022-07-24 14:56
Duplicate of #542

We're looking into it, thank you for the detailed report.

**Closed by MichaelHillcox** 2022-07-24 14:56 UTC
