### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by void206551** [FTBTeam/FTB-App#314] opened 2020-10-21 23:19 UTC
**Operating System:**
OS: Windows 10 Pro

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
https://pste.ch/gabiwuyoru

**Describe the bug**
The example modpack in the settings will have option to install and if trying to install will stay on 'Creating environment...'

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Settings'
2. Scroll to 'App Display'
3. Click on the download option for the 'Example Modpack'
4. On the popup to install, press 'Install'
5. See error

**Expected behaviour**
For this to not install or have no option to install. 

**Screenshots**

![Install Popup](https://user-images.githubusercontent.com/32175146/96799937-2b924c00-13d2-11eb-9da6-3a8985229e5a.png)

![Creating Environment](https://user-images.githubusercontent.com/32175146/96799905-17e6e580-13d2-11eb-8708-1fdf96e5f8f8.png)

**Comment by Rushmead** [comment] 2020-10-21 23:55
This is a duplicate of #249, closing :)

**Closed by Rushmead** 2020-10-21 23:55 UTC
