### ISSUE TITLE
[Bug]: Fatal exception while installing modpack

### ISSUE THREAD

**Issue by goofygabe8** [FTBTeam/FTB-App#629] opened 2022-07-07 04:36 UTC
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Log Files

https://pste.ch/izolilociq

### Debug Code

FTB-DBGOJUSUZEYET

### Describe the bug

When ever I try to download a modpack it says "Fatal exception whilst installing modpack"

### Steps to reproduce

1. Find any modpack and click on it
2. Start to download the modpack
3. Should pop up with an error window saying "Fatal exception whilst installing modpack"

### Expected behaviour

Should download modpack

### Screenshots

![image](https://user-images.githubusercontent.com/80008985/177691930-77cc86ce-f562-40ce-9aca-05292f0410e5.png)

### Additional information

I'm actually on windows 11 but it doesn't give me the option to put that 

### Information

- [X] I have provided as much information as possible

**Comment by Tuho89** [comment] 2022-07-12 07:20
Hey mate, 
I have the same issue, but might have found the reason for it. 
Could you test it like me and write your finding?
https://github.com/FTBTeam/FTB-App/issues/633

Basically, download and check if you have this issue with EVERY modpack? or only modpacks that have BETA versions?

**Comment by MichaelHillcox** [comment] 2022-07-24 15:34
Duplicate of #479

**Closed by MichaelHillcox** 2022-07-24 15:34 UTC
Labels: bug
