### ISSUE TITLE
[Bug]: Valhelsia: Enhanced Vanilla - 1.18 failure to install

### ISSUE THREAD

**Issue by iamtimsson** [FTBTeam/FTB-App#581] opened 2022-05-30 20:09 UTC
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Log Files

https://pste.ch/uboqavinat

### Debug Code

FTB-DBGSOQOCIPAQO

### Describe the bug

Failure to install seemingly based on colon in file name

### Steps to reproduce

Browse, search curseforge for valhelsia, download Valhelsia Enhanced Vanilla-1.2.3, failure to install - check logs

### Expected behaviour

Install successfully

### Additional information

End of debug log reads:
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 9: Valhelsia: Enhanced Vanilla - 1.2.3-overrides.zip

### Information

- [X] I have provided as much information as possible

**Comment by iamtimsson** [comment] 2022-05-30 21:20
This bug also affects SevTech: Ages and SevTech: Ages of the Sky

**Comment by devExcale** [comment] 2022-07-05 19:39
Has there been any update on this? I just run into this bug with SevTech, I'd like to install the modpack.

Unfortunately, I don't know how FTB works, but this doesn't seem hard to fix. My guess is that the launcher tries to save the zip file, but the filename has illegal characters in it, so it can't save it.

Imo this is not a small bug, as it would make any modpack with illegal/strange characters in it fail to install, leaving no choice but to try other launchers.

**Comment by UnknownForTheForce** [comment] 2022-07-11 23:57
I have a problem, the game not detect the mod creative core, when it is installed, i downloaded the 1.18.2 version in game. i tryied to install another version of the mod but its the same.

**Comment by MichaelHillcox** [comment] 2022-07-24 14:44
Please can you retry now as we've just updated some things that should have resolved these issues

**Comment by MichaelHillcox** [comment] 2022-07-27 15:39
Duplicate of #558

**Closed by MichaelHillcox** 2022-07-27 15:39 UTC
Labels: awaiting response
