### ISSUE TITLE
cant lauch FTB

### ISSUE THREAD

**Issue by hunterwep1** [FTBTeam/FTB-App#892] opened 2023-04-16 09:44 UTC
### What Operating System

Windows 10

### Debug Code

FTB-

### Describe the bug

cant start

### Steps to reproduce

cant start 

### Expected behaviour

cant start it up

### Screenshots

![Naamloos](https://user-images.githubusercontent.com/130899503/232290397-86480e1c-5186-4832-8a31-e9e5b7cba164.png)

### Additional information

can you help me

**Comment by MichaelHillcox** [comment] 2023-06-22 20:40
Closing, no debug code supplied. Duplicate of #890

**Closed by MichaelHillcox** 2023-06-22 20:40 UTC
Labels: bug
