### ISSUE TITLE
Fails to set new Instance Location in FTB App Settings.

### ISSUE THREAD

**Issue by Lightshardz** [FTBTeam/FTB-App#1028] opened 2023-12-05 17:39 UTC
### What Operating System

Windows 11

### Debug Code

FTB-DBGWAYINIFUQU

### Describe the bug

  Installed Overwolf to D: drive. Installed FTB App (no option to change install location to new folder/location.......). Open FTB App, go to Settings, try to change Default Instance Location from standard users/AppData folder to D:\FeedTheBeast/Instances. Get an error "New location is not writable by the FTB App.".  My C: drive is dedicated to OS, and the users folder is backed up to OneDrive, and I do not want this size of data being backed up there. I have CurseForge and other Games all installed to the D: drive with no issue. There is no security permissions, I tried launching both Overwolf and FTB App as Administrator to see if that fixed, and still receive the same error.
  I installed a modpack and tried to force it to change directly rather than the default instance. It "half" worked, as in when I looked in the D: folder there were files there related to the specific instance of the modpack, however when I go to the modpack in the FTB App and select "Open Instance Folder" it still takes me to AppData folder.
    I tried creating a folder on my E: drive (normally my backup -- large SSD, where D: is a. M.2 NVME with fast r/w speeds), and get the same error. I even tried creating a C:\FTBApp\Instances folder and setting there, and get the same error.

### Steps to reproduce

1. In FTB App go to Settings
2. Under Instances, scroll down to "Misc/Instance Location" and change using the "Browse" button to any other location.
3. Receive "New location is not writable by the FTB App" error and no change to the instance location.

### Expected behaviour

Sets new Instance Location to specified folder.

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/77556352/cf06e46f-6458-472e-8961-88dd803bd8b6)

### Additional information

[12:33:34] [ForkJoinPool-1-worker-2/INFO] [net.creeperhost.creeperlauncher.api.handlers.instances.MoveInstancesHandler]: Preparing to move instances from C:\Users\jerem\AppData\Local\.ftba\instances to E:\FTBApp\Instances
[12:33:34] [ForkJoinPool-1-worker-2/WARN] [net.creeperhost.creeperlauncher.api.handlers.instances.MoveInstancesHandler]: New location E:\FTBApp\Instances is not writable by the app
[12:34:44] [ForkJoinPool-1-worker-2/INFO] [net.creeperhost.creeperlauncher.api.handlers.instances.MoveInstancesHandler]: Preparing to move instances from C:\Users\jerem\AppData\Local\.ftba\instances to C:\FTBApp\Instances
[12:34:44] [ForkJoinPool-1-worker-2/WARN] [net.creeperhost.creeperlauncher.api.handlers.instances.MoveInstancesHandler]: New location C:\FTBApp\Instances is not writable by the app
[12:38:50] [ForkJoinPool-1-worker-2/INFO] [net.creeperhost.creeperlauncher.api.handlers.instances.MoveInstancesHandler]: Preparing to move instances from C:\Users\jerem\AppData\Local\.ftba\instances to D:\FeedTheBeast\Instances
[12:38:50] [ForkJoinPool-1-worker-2/WARN] [net.creeperhost.creeperlauncher.api.handlers.instances.MoveInstancesHandler]: New location D:\FeedTheBeast\Instances is not writable by the app

[latest.log](https://github.com/FTBTeam/FTB-App/files/13565193/latest.log)

**Comment by MichaelHillcox** [comment] 2023-12-05 22:19
This is intended behaviour. Although, the D:/ should work tbh. The C:/ won't as that's a protected area. Try and move it to somewhere within your user directly, if this doesn't work, let me know and I'll see if I can figure out why it's not working

**Comment by MichaelHillcox** [comment] 2023-12-06 01:12
Sorry, to be clear, the intended behaviour is for it to halt the migration to folders it can not write to. I will look into this one windows as it may be a weird window issue...

**Comment by Lightshardz** [comment] 2023-12-06 04:11
@MichaelHillcox I understand an original intended behavior to not be able to set to write-protected, or security protected folders, however this is not the case here. This is ANY folder change, even when running as administrator, and the newly created folders under the D:\ or E:\ drive I even tried (temporarily) setting security permissions to "Allow" for full control, with no luck. And it's ONLY this app that has issues writing to that folder. Curseforge (another Overwolf app) has no issue changing to the D:\ drive, just to give an example of a similar app that works.

I tried creating a folder under "C:\users\[MyUser]\Feed the Beast\Instances" and I get the same error. No matter where I create a folder, it will not change locations. I even tried to create an identical folder in the same AppData, and it won't switch to that either, ie. "C:\Users\[MyUser]\AppData\Local\.ftba2\instances". The whole reason I want to move it to my D: drive is due to my whole Users folder is set to OneDrive cloud sync, and I do not want this there.

**Comment by fatihyaman661** [comment] 2023-12-06 12:57
The same problem here on linux, pop os! distro. Wherever I try to change the instances, it just gives the same error

**Comment by MichaelHillcox** [comment] 2023-12-06 15:21
I've found the issue and should have it fixed in the next update. Looking to ship it today so I'll update this post once it's out

**Comment by MichaelHillcox** [comment] 2023-12-06 22:38
Version should be shipped now, you can update early using this link:

https://dist.creeper.host/FTB2/cdn/app/opks/FTB%20App_1.23.1206.2219.opk

**Closed by MichaelHillcox** 2023-12-06 22:38 UTC
Labels: bug, fixed/dev, awaiting response
