### ISSUE TITLE
FTB App resets instances folder after Update

### ISSUE THREAD

**Issue by Yijare** [FTBTeam/FTB-App#1127] opened 2024-05-24 00:16 UTC
### What Operating System

Windows 10

### Debug Code

not applicable

### Describe the bug

The FTB App, after Updating resets the Location of the instances folder to /AppData/local/

### Steps to reproduce

Open App
Get an App Update
see your instances 'vanish'

### Expected behaviour

no reset of folder localtion

**Comment by Yijare** [comment] 2024-05-24 00:18
The debuger you 'provide' is flagged as malicious by windows defender and malewarebytes. not happening.

**Comment by WyFryMU** [comment] 2024-05-24 01:06
https://www.virustotal.com/gui/file/a59aa420cc22a5eae67a110586d9f6f0f03eb398a5cf4d39200f8421cbdbe543
No virus' detected. It's what they use. Otherwise go into your ftb app, go to settings, click App, then click Upload Logs and paste the link here.

**Comment by incomingnerd** [comment] 2024-05-25 13:48
I am also seeing the same behaviour since the latest update. To reproduce:

1. Open the FTB App
2. Relocate the instances folder (in my case to my games drive `E:\FTBInstances`)
3. Close the app
4. Re-open the app - the instances folder has reset back to `%localappdata%\.ftba\instances`

Whatever recently got changed in the config handler logic needs bug checking/reverting.

**Comment by incomingnerd** [comment] 2024-05-25 13:54
When would you like the debug logs to be taken? Just after changing the instances folder? After the app restart, when the folders reset?

**Comment by MichaelHillcox** [comment] 2024-06-01 19:29
> I am also seeing the same behaviour since the latest update. To reproduce:
> 
> 1. Open the FTB App
> 2. Relocate the instances folder (in my case to my games drive `E:\FTBInstances`)
> 3. Close the app
> 4. Re-open the app - the instances folder has reset back to `%localappdata%\.ftba\instances`
> 
> Whatever recently got changed in the config handler logic needs bug checking/reverting.

Could you send over the settings.json from /storage in the .ftba folder after you have edited the config but before you close the app, then the same file after closing the app, then again after starting the app?

**Comment by incomingnerd** [comment] 2024-06-05 15:59
The bug seems to have now vanished for me (fingers crossed). I wasn't keeping track of app versions (my bad) so there may have been an update pushed that I didn't notice. The only other thing I've done since was update my NVIDIA drivers, Windows Update and reboot a few times.

**Closed** 2024-06-06 13:07 UTC
Labels: bug
