### ISSUE TITLE
Add a way to look through curseforge packs

### ISSUE THREAD

**Issue by MooMcMooman** [FTBTeam/FTB-App#1030] opened 2023-12-05 21:14 UTC
### What is your suggestion?

It might bring in a few people, but most importantly, it would help while looking for a pack. Right now the current situation is you have to know the name of the pack, but, most of the time, people don't know what pack they are looking for.

**Comment by MichaelHillcox** [comment] 2024-06-06 16:50
Sorry, just noticed this is a duplicate of #416, closing in preference of that one

**Closed by MichaelHillcox** 2024-06-06 16:50 UTC
Labels: status: planned, feature:request
