### ISSUE TITLE
[Feature request] Add a modlist visible before installing a pack

### ISSUE THREAD

**Issue by HLightning11** [FTBTeam/FTB-App#209] opened 2020-07-19 23:56 UTC
I like to look for a few key mods or just try to get a feel for the kinds of mods in a pack, but the way the launcher is currently set up, you have to install a pack before you can view a full modlist, which takes time, space, and internet.
Therefore, it would be nice to have access to a full modlist before installing a pack.
This list could be like the one you see after installing the pack, or all the mods added in the release as an update.
I could be missing something, so if this already exists, please let me know. (Also, apologies if the writing is weird. The template put me in "structured essay" mode.)

**Comment by Gaz492** [comment] 2020-07-20 20:40
This is on our todo list as this is a duplicate of #168 I will close this.

**Closed by Gaz492** 2020-07-20 20:40 UTC
