### ISSUE TITLE
[Bug]: Instance failure

### ISSUE THREAD

**Issue by Faxoo14** [FTBTeam/FTB-App#541] opened 2022-05-10 14:52 UTC
### What Operating System

Windows 10

### App Version

202204211116-ac2e189d70-release

### UI Version

ac2e189d70

### Log Files

https://pste.ch/uwefivabex

### Debug Code

FTB-DBGMAWOSASUNI

### Describe the bug

I just want to play FTB Lite. Always if I push the play button it crashs and i get these Messages (see in Screenshot)

### Steps to reproduce

1. Go to Libary and Click on FTB LIte 
2. Then click play
3. Error ( See in Screenshot)

### Expected behaviour

I only want to play this Game

### Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/105300171/167657262-8011d37c-571e-4ba4-9b21-1f15866adf64.png)

### Additional information

I already reinstall FTB and Minecraft but nothing happens

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment] 2022-07-24 13:23
Duplicate of #479

**Closed by MichaelHillcox** 2022-07-24 13:23 UTC
Labels: bug
