### ISSUE TITLE
[Feature] Linux installer options

### ISSUE THREAD

**Issue by Hero9909** [FTBTeam/FTB-App#217] opened 2020-07-24 14:26 UTC
For performance and storage reasons im using an java version of sdkman. the ftb installer does not seems to have any options to prevent installing the bundled jre. 

an simple option to override would help. for support the app could generate a simple system info wich includes if a custom java is used

**Comment by Gaz492** [comment] 2020-10-21 20:28
I'll close this as its more or less a duplicate of #215

**Closed by Gaz492** 2020-10-21 20:28 UTC
