### ISSUE TITLE
[Bug]: FTBInstall.sh on CurseForge port uses outdated download link

### ISSUE THREAD

**Issue by warriorjacq9** [FTBTeam/FTB-App#742] opened 2022-11-14 16:21 UTC
### Modpack

FTB Infinity Evolved

### Modpack version

3.1.0

### Log Files

[Log file of run](https://pastebin.com/jBRRtc2P)

### Describe the bug

The FTBInstall.sh file in the CurseForge download of this modpack drove me crazy by using the outdated download link https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/minecraft_server.1.7.10.jar. Maybe update it to http://www.mc-download.com/index.php?action=downloadfile&filename=minecraft-server-1.7.10.jar&directory=Minecraft%20Versions%20Official/Minecraft%20Server& ?

### Steps to reproduce

1. Go to [this link](https://www.curseforge.com/minecraft/modpacks/ftb-infinity-evolved)  and download the zip file.
2. Run FTBInstall.sh or .bat
3. Use ```file``` or equivalent to see what type the vanilla server jar is.
4. It comes out as: XML ASCII Text

### Expected behaviour

```file``` outputs Zip archive data

### Additional information

This caused me hours of searching about a minecraft server failing before I thought to check the vanilla server jar. It would be very helpful if this was fixed.

**Comment by MichaelHillcox** [comment] 2022-11-30 11:13
Duplicate of #748 should be fixed in the next release

**Closed by MichaelHillcox** 2022-11-30 11:13 UTC
