### ISSUE TITLE
[Bug] Launching modpack gives "Freshly updated launcher crashed" on console; no actionable diagnostic

### ISSUE THREAD

**Issue by pwaller** [FTBTeam/FTB-App#403] opened 2021-04-09 16:15 UTC
**Operating System:**
OS: Ubuntu 20.04

**Installer Version:**
Installer: ??, installed a while ago, I don't know.

**App Version:**
App: 202104081147-534c2a1ea3-release

**UI Version:**
UI: 6f769022

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Start FTBApp
2. Attempt to run a modpack
3. A dialog appears showing an update, for a fraction of a second (fast enough I haven't been able to screenshot it)
4. A larger window appears, again, only for a frame or so.
5. Nothing.
6. Console output below: `Launcher crashed while executing... signal: 5`

```
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [Info: 2021-04-09 16:12:07.217616382: mainLinux.cpp(244)] Update complete.
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [Info: 2021-04-09 16:12:07.218146198: WindowGTK.cpp(41)] Closing the window
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [Info: 2021-04-09 16:12:07.218169575: NetQueue.cpp(183)] NetQueue: Initiating shutdown.
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [Info: 2021-04-09 16:12:07.218185399: NetQueue.cpp(188)] NetQueue: No thread currently running
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [Info: 2021-04-09 16:12:07.218198439: mainLinux.cpp(500)] Attempting to start the launcher
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [Info: 2021-04-09 16:12:07.218215004: mainLinux.cpp(118)] Window closing, exiting process
[17:12:07] [ForkJoinPool.commonPool-worker-27/INFO] [Minecraft Launcher 5]: https://launchermeta.mojang.com/v1/products/launcher/bb3355e087ada56549e6342233b57bf65d9d7147/linux.json
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [0409/171207.497876:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 1 time(s)
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [0409/171207.498467:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 2 time(s)
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [0409/171207.498898:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 3 time(s)
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [0409/171207.499353:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 4 time(s)
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [0409/171207.499721:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 5 time(s)
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [0409/171207.500075:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 6 time(s)
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [0409/171207.500457:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 7 time(s)
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [0409/171207.501949:INFO:main_context.cpp(136)] CEF initialized successfully.
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [0409/171207.501975:INFO:main_context.cpp(138)] CEF version: 86.0.23+ga2c2edf+chromium-86.0.4240.193
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [0409/171207.788368:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 8 time(s)
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: Created browser window for reuse: 0x3a00001
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [0409/171207.807498:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 9 time(s)
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [0409/171207.807513:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [Fatal: 2021-04-09 16:12:07.811686116: mainLinux.cpp(508)] Launcher crashed while executing... signal: 5
[17:12:07] [ForkJoinPool.commonPool-worker-9/ERROR] [Minecraft Launcher 5]: [Info: 2021-04-09 16:12:07.811741812: mainLinux.cpp(511)] Freshly updated launcher crashed.
```

**Expected behaviour**
The game should launch.

**Screenshots**
No relevant screenshots, the intermediate dialogs/windows only appear for a very brief time

**Additional context**
None.

**Comment by pwaller** [comment] 2021-04-09 16:59
I have reproduced this on an independent machine.

I also happened on a workaround: running ~/.ftba/bin/launcher/minecraft-launcher in a shell allows the update dialog which pops up to run to completion, and then you're presented with a UI (missing the mod). However, after that, retrying FTB works.

**Comment by basneder** [comment] 2021-04-17 00:04
I have the same issue. The work-around works for me as well

**Comment by joksan** [comment] 2021-05-02 06:37
Same issue and same fix too.

**Comment by Arimodu** [comment] 2021-06-05 16:54
same here, fix also works for the launcher, but then I run into a different issue after starting the game. Gonna google around for that

**Comment by man0ca** [comment] 2021-06-30 20:23
same behaviour. Fix is working too all the way into the game. No further issues(until now :D)

**Comment by MichaelHillcox** [comment] 2021-07-04 19:44
The log looks to think that the GPU is not available. Are you running the app in a virtualised enviroment? (snap / other)

**Comment by Arimodu** [comment] 2021-07-04 20:31
> The log looks to think that the GPU is not available. Are you running the app in a virtualised enviroment? (snap / other)

For me this issue happened when running on a laptop with hybrid GPUs, my desktop with a single GPU didnt have said issue

**Comment by basneder** [comment] 2021-07-04 20:37
> The log looks to think that the GPU is not available. Are you running the app in a virtualised enviroment? (snap / other)

For me it happened on my desktop not virtualized or anything, nvidia (GeForce RTX 2070 SUPER) as GPU using the nvidia drivers

**Comment by LeoColman** [comment] 2021-07-31 02:53
Confirm this happened on a desktop with a single GPU, GeForce GTX 1660 SUPER, using nvidia drivers. Also fixed by the workaround provided:

> running ~/.ftba/bin/launcher/minecraft-launcher in a shell allows the update dialog which pops up to run to completion, and then you're presented with a UI (missing the mod). However, after that, retrying FTB works.

**Comment by fosspill** [comment] 2021-08-16 18:03
Same error and same workaround on voidlinux with mesa on AMD.

**Comment by Radagast** [comment] 2021-09-26 23:44
From what I can understand this is related to Electron Apps built on Chromium which missed a commit and is glibc related. There details and and a fix [here](https://github.com/electron/electron/pull/31091) for Electron >= 14 and it's being back-ported to 13. This is also breaking the discord app, at least for me on Tumbleweed.

**Comment by Jul1111** [comment] 2021-11-01 20:16
I have the same error but i cant run /.ftba/bin/launcher/minecraft-launche because i dont have a file with this name

**Comment by dkowis** [comment] 2021-11-12 20:59
Just hit me, PopOS 21.10, single GPU on my desktop.

**Comment by Blacksmoke16** [comment] 2022-01-03 05:23
Can confirm the suggested workaround resolves the issue. I'd say this is a confirmed issue at this point. 

Installed it via Aur on Arch.

**Closed** 2022-02-11 15:10 UTC
Labels: bug, os/linux, unconfirmed
