### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by raflowers** [FTBTeam/FTB-App#509] opened 2022-03-27 16:34 UTC
### What Operating System

Windows 10

### App Version

202203051730-9df8355f62-release

### UI Version

9df8355f62

### Log Files

https://pste.ch/mosasimogu

### Debug Code

FTB-DBGMEDETOPEME

### Describe the bug

I have the latest Direwolf20 pack installed and have been playing it for a couple of weeks now. This morning the FTB app via Overwolf is not showing that I have DW20 installed even though I can still find the instance on my drive in the folder where all my other instances are stored.

### Steps to reproduce

1. Open FTB App
2. Not all installed instances are listed as installed

### Expected behaviour

I should see that Direwolf20 is installed and available to play

### Screenshots

![LIbrary screenshot](https://user-images.githubusercontent.com/48536856/160291339-ef32f628-3a77-4a6c-9999-b878fa3ed324.png)

### Additional information

I tried just hitting install on the DW20 pack again but it created a separate instance that didn't have my worlds/settings etc

### Information

- [X] I have provided as much information as possible

**Comment by raflowers** [comment] 2022-03-27 17:00
Now when I try to installed the latest DW20 pack - thinking I could just move my world over and deal with any issues that created - the FTB app tells me "The modpack failed to install"

**Comment by MichaelHillcox** [comment] 2022-07-24 13:05
Duplicate of this issue #534

Thank you for your report, we'll handle any future communication in #534 hopefully we can figure out why this is happening. What I can tell you is that your world will be safe. You can find it at `C:/Users/yourusername/appdata/local/.ftba/instances` simply reinstalling the pack and copying your world over should solve this in the short term.

Sorry for the slow reply here

**Closed by MichaelHillcox** 2022-07-24 13:05 UTC
Labels: bug
