### ISSUE TITLE
Ads appear on top of the the versions pop-up of a modpack and can block some content

### ISSUE THREAD

**Issue by Poopooracoocoo** [FTBTeam/FTB-App#903] opened 2023-04-19 11:14 UTC
### What Operating System

Windows 10

### Debug Code

FTB-DBGOMAYIYAZOK

### Describe the bug

Ads appear on top of the the versions pop-up of a modpack and can block some content

### Steps to reproduce

1. Open FTB App
2. Navigate to Browse tab
3. Click on a modpack
4. Click on 'versions'

### Expected behaviour

Versions pop-up appears above ads, or versions are displayed as a page.

### Screenshots

![image](https://user-images.githubusercontent.com/51363864/233057648-fb153991-99be-4ba8-9b83-ae00664cbf54.png)

### Additional information

UI version: 91bb027b9e
App version: 202304121437-91bb027b9e
Overwolf client version: 0.221.0.4
Windows 10 22H2

**Comment by MichaelHillcox** [comment] 2023-06-22 20:30
duplicate of #908 

Closing to compact but thanks for the report

**Closed by MichaelHillcox** 2023-06-22 20:30 UTC
Labels: bug
