### ISSUE TITLE
[Bug] Authorization Failed 

### ISSUE THREAD

**Issue by AllHopeLost** [FTBTeam/FTB-App#86] opened 2020-04-11 20:33 UTC
**Operating System:**
OS: Windows 10 Pro N 
Version: 1909
Build: 18363.720 

**Installer Version:**
Installer: FTBA_windows-x64_1_0_6

**App Version:**
App: c84af858

**UI Version:**
UI: 1.0.6

**Log Files:**
https://pste.ch/itiseyanex

**Describe the bug**
Attempting to download the Direwolf20 2.6.0 Server pack regardless of OS selected. browsers displays a white screen with this text `{"status":"error","message":"Authorization failed.","userKey":null}`

**To Reproduce**
Download server pack through FTB launcher 

**Expected behavior**
Server pack download of direwolf20 2.6.0

**Screenshots**

**Additional context**

**Comment by Cloudhunter** [comment] 2020-04-11 23:26
Duplicate of #84

**Closed by Cloudhunter** 2020-04-11 23:26 UTC
