### ISSUE TITLE
[Bug] Modpacks don't use the room they have unless given even more room

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-App#105] opened 2020-04-16 20:19 UTC
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: I don't know how to find this

**App Version:**
App:  1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
https://pste.ch/uqogidozav 

**Describe the bug**
![](https://cdn.discordapp.com/attachments/369881656930205701/700437148591194162/unknown.png)
There's plenty of room for two more modpacks right there.
![](https://cdn.discordapp.com/attachments/369881656930205701/700437165024215150/unknown.png)
Expanding the window a tiny amount horizontally makes Academy pop in

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Browse on smallest window size
2. Expand the horizontal area

**Expected behaviour**
It should put as many tiles as there's room for, or just cut off at one line.

**Comment by Jake-E** [comment] 2020-04-16 20:24
Duplicate of #76.

**Closed by Jake-E** 2020-04-16 20:24 UTC
