### ISSUE TITLE
[Bug]: Installed instances have disappeared from app library

### ISSUE THREAD

**Issue by ShyMaiden** [FTBTeam/FTB-App#599] opened 2022-06-08 17:36 UTC
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Debug Code

FTB-DBGUSUBUCUGAV

### Describe the bug

Installed instances have disappeared from app library

### Steps to reproduce

I am not sure how to reproduce it, because it happens only occasionally and I can't think of what I do differently to cause the problem

### Expected behaviour

My installed instances available in the library when opening the app

### Screenshots

The site doesn't let me add my screenshots...

### Additional information

But what happens is I start the app and expect (as it does most times) that my installed packs are visible in my library. But occasionally, it says I have nothing installed. When I check the folder on my computer in windows explorer, everything is there.
I have fixed the problem before by going to settings and setting the instance folder to the one my instances are in, closing the app and restarting it. This hasn't worked today.
I do notice that the instance location is empty again when I restart the app.

### Information

- [X] I have provided as much information as possible

**Comment by ShyMaiden** [comment] 2022-06-08 17:50
Small update: I managed to get things working again by doing the move instance location thing, download a new pack and suddenly the app recognized I had other instances too. Glad I can go back to playing, but I'd love to not have to resort to such workarounds

**Comment by Greenshark3D** [comment] 2022-06-11 10:13
I have a similar problem. In the launcher I have 4 modpacks. In file explorer I have 5 modpacks. The modpack that I am missing is: "FTB Presents Direwolf20 1.18. I have identifide the pack that I am missing in file explorer

**Comment by ShyMaiden** [comment] 2022-06-15 18:06
and once again, everything is gone. new logs:
https://pste.ch/ledujihiti

**Comment by MichaelHillcox** [comment] 2022-07-24 14:54
Duplicate of #534 

I can ensure you we're looking into this and trying to find the cause

**Closed by MichaelHillcox** 2022-07-24 14:54 UTC
Labels: bug
