### ISSUE TITLE
Failed to prepare instance FTB Stoneblock 3

### ISSUE THREAD

**Issue by Kamiferbo** [FTBTeam/FTB-App#806] opened 2022-12-18 12:07 UTC
### What Operating System

Windows 10

### Debug Code

the Deguber Give me no code

### Describe the bug

When i start to play StoneBlock 3 modPack Start to pre-Start de modPack but before that finish, the error 'An error ocurred Whilst launching' pop and stop trying to launch the modpack

### Steps to reproduce

1. go to home on the app
2. click play on the Stoneblock 3 ModPack
3. wait for the error

### Expected behaviour

i expect to dont pop an error when the modPack is launching

### Screenshots

![Erorr-FTB](https://user-images.githubusercontent.com/120930336/208297285-753e03e9-67d7-4d0f-ac49-288f613b9141.jpg)

### Additional information

the error happen after i have a disconection mid game because a blackout.
And i run the Debug Code and no code is given to me

**Comment by TripleA97** [comment] 2022-12-18 13:44
Same error since yesterday

**Comment by Kamiferbo** [comment] 2022-12-18 22:52
the problem solve by itself i do nothing and now i run  normally

**Comment by TripleA97** [comment] 2022-12-18 23:10
Same

**Comment by covers1624** [comment] 2022-12-19 04:01
We are unable to assist without a debug code.

However, it sounds like this issue has resolved itself. Based on the little information in the above screenshot, this could have been caused by a momentary network outage.

I will close this issue.

**Closed by covers1624** 2022-12-19 04:01 UTC
Labels: bug
