### ISSUE TITLE
Enable Cloud Sync[Bug]: 

### ISSUE THREAD

**Issue by tjoseph67** [FTBTeam/FTB-App#557] opened 2022-05-20 21:11 UTC
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Debug Code

 FTB-DBGOWUHOSELAJ

### Describe the bug

I have an active plan with mine together. the enable cloud saving is still grayed out in the laucher 

### Steps to reproduce

Download FTB Launch 
Do everything to get a mine together account
see if the slide is active 

### Expected behaviour

a fix so i can play on game files on other systems 

### Screenshots

![Screenshot 2022-05-20 171209](https://user-images.githubusercontent.com/105949538/169611059-e587a994-ced4-4a23-ac01-f9a3415262b6.png)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment] 2022-07-24 14:06
Duplicate of #465

We're working on getting this working again

**Closed by MichaelHillcox** 2022-07-24 14:06 UTC
Labels: bug

**Comment by shank3001** [comment] 2023-02-15 08:32
How is this closed when it is still an issue?

**Comment by MichaelHillcox** [comment] 2023-02-15 10:57
It's a duplicate, we know this is still an issue, and we're actively still working on it, but there is no reason to have multiple issues stating the same thing.
