### ISSUE TITLE
[Bug]: error! unable to update, validate or find your profile, please sign in again.

### ISSUE THREAD

**Issue by brezxx** [FTBTeam/FTB-App#709] opened 2022-11-04 03:04 UTC
### What Operating System

Windows 10

### Debug Code

d

### Describe the bug

its saying when I click on the mod pack I want to play error! unable to update, validate or find your profile, please sign in again.

### Steps to reproduce

d

### Expected behaviour

d

### Screenshots

d

### Additional information

d

### Information

- [X] I have provided as much information as possible

**Comment by Fade-Alchemist** [comment] 2022-11-05 20:49
Same here- I was able to get in yesterday (with much difficulty) Now this is all I get

![image](https://user-images.githubusercontent.com/29619427/200140723-970eb2db-8902-4d96-b3f5-7691f1d35d19.png)

**Comment by Aromatico** [comment] 2022-11-08 02:56
remove your account from the launcher if it is from Microsoft enter in the Mojang area making a mistake on purpose and log in again with the Microsoft account

**Comment by Aromatico** [comment] 2022-11-08 02:56
remove your account from the launcher if it is from Microsoft enter in the Mojang area making a mistake on purpose and log in again with the Microsoft account

**Comment by Zppj0** [comment] 2022-11-08 03:29
Still did not work for me

**Comment by ZipZ0p** [comment] 2022-11-08 03:29
I have the same problem.  When I remove my account and sign back in still gives me the error message.

**Comment by JasonWBridgeTown** [comment] 2022-11-08 06:38
Ditto.   I removed my account from the FTB app, re-logged into my MS account, and the FTB app does not recognize the login.

**Comment by Aromatico** [comment] 2022-11-08 06:53
> 

Try  to log in with Mojang account even if you are not using Mojang 
Then try again to log in with Microsoft

**Comment by Sperex689** [comment] 2022-11-08 07:17
![dsadsaads](https://user-images.githubusercontent.com/117714598/200499190-6227ef18-def3-4fd8-ac51-2a18a55ab931.PNG)




same problem

**Comment by KillerBunny1342** [comment] 2022-11-08 08:28
The Official Mojang Server is having issues so u have to wait until it gets resolved

**Comment by amsolano426** [comment] 2022-11-08 17:13
My account was working fine 2 days ago (11/06/22).  Then yesterday (11/07/22) I got nothing, and same today.  All my screen are verbatim what has been posted above.  Is it really a mojang server issue?  I looked at https://www.isitdownrightnow.com/ and searched for mojang and got that "The site has been unreachable for more than 490 days. If the site is live or if you have further information about the site status, please comment below."...granted I searched for mojang.com, so when Microsoft bought them the dot com probably went away, but I figured the server would still ping or something.  But nope...  I am in realy need of my minecraft fix lol...

**Comment by tim2020ua** [comment] 2022-11-18 07:48
It worked well yesterday (17.11), but now i can't do anything. I've tried to re-enter in microsoft but it gives me this
![image](https://user-images.githubusercontent.com/70541347/202648710-022dcd1e-8069-4d9f-8e55-76fea954a1df.png)
and i can't enter in mojang account because i migrated to microsoft account/ Does it problem with microsoft servers?

**Comment by Thimax11** [comment] 2022-11-18 10:06
Register with microsoft are back, try it

**Comment by BTNGaming** [comment] 2022-11-18 20:05
Still not working.

**Comment by spenhsef** [comment] 2022-11-19 00:55
having a very similar issue. i get the "unable to find profile" error, so i signed out. but the issue is logging back in. i cannot through mojang because i migrated and microsoft isnt actually validating. i sign in through microsoft on my browser and it says it should sign in on the app, but it doesnt.

**Comment by SuperNova1440** [comment] 2022-11-19 19:42
I used a VPN and it worked. I think Microsoft is having issues validating accounts

**Comment by elovien** [comment] 2022-11-20 14:16
Can confirm that VPN fixes the issue. I closed out of the FTB app, set my VPN to the USA (I live in Europe). When I opened up FTB again - no problems with logging in or starting a modpack, no error messages

**Comment by MichaelHillcox** [comment] 2022-11-30 11:47
Should be fixed now

**Closed by MichaelHillcox** 2022-11-30 11:47 UTC
Labels: bug

**Comment by galleronus** [comment] 2022-12-01 12:51
It is.  Thanks!
________________________________

**Comment by infinitefreebeer** [comment] 2023-01-16 04:51
So, I had this problem. My Microsoft Account based on my email has one password, my Minecraft Account attached to that email account has a different password, and my phone number attached to both of those accounts has another password. None of those... sub-accounts, will accept passwords from another sub-account affiliated with the parent account. FTB would only allow me to sign in under my phone number, then it allowed my Minecraft Account without the password. What.
