### ISSUE TITLE
stoneblock 3  Launch bug

### ISSUE THREAD

**Issue by matt14509** [FTBTeam/FTB-App#862] opened 2023-02-17 15:45 UTC
### What Operating System

Windows 10

### Debug Code

FTB-DBGKEREWOCUMA

### Describe the bug

https://apps.modepacks.ch/meta.json is not work

### Steps to reproduce

1. Launch FTN app
2. install stoneblock 3
3.   Launch stoneblock 3

### Expected behaviour

apps.modepacks.ch down

### Screenshots

![image](https://user-images.githubusercontent.com/88714707/219700044-473e8b6c-be96-4729-8f8c-b0bbbad13994.png)

**Comment by mrgrumbly** [comment] 2023-02-17 17:44
I am having the same issue with the Direwolf20 modpack. I also tried install a new modpack to see if the issue was modpack-specific but the FTB App won't let me install anything.

**Comment by NateChambers** [comment] 2023-02-17 17:53
This isn't specific to stoneblock 3 at all. All 13 modpacks I try to open today, shows this error.

**Comment by DoctorWillis** [comment] 2023-02-18 11:06
I have the same issue, with identical error output.
Neither of my FTB instances will launch, whereas instances launching from CurseForge (eg, Sky Factory 3) do

**Comment by adrimax11** [comment] 2023-02-18 15:52
The problem occurs when you have Kaspersky antivirus, close it and try again. It has worked for me doing that

**Comment by NateChambers** [comment] 2023-02-18 16:38
> 

Disabling your anti-virus is **TERRIBLE** advise mate. Especially for those of us always traveling/on public wifi.

Where is a real fix for this, it's been over 24 hours!!??

**Comment by mrgrumbly** [comment] 2023-02-18 20:05
I tried disabling the anti-virus and I still get the same errors.

**Comment by DoctorWillis** [comment] 2023-02-19 02:40
I paused Kaspersky and attempted running SB3, but it made no difference and I still get the same error as above

**Comment by matt14509** [comment] 2023-02-19 07:02
Not only Kaspersky have this issue, windows defender too.

**Comment by mrgrumbly** [comment] 2023-02-20 19:56
** Kaspersky Users **
 Go into Kaspersky Settings - Down to Network settings - Un-Check box next to "Support DNS over HTTPS (DoH) - Save Settings at bottom of the window - Close FTB App - Re-open FTB App and try your modpack again. 

I will say this fixed it but I am not sure what exactly this does. I got this information from the FTB Discord under ftb app support and the information was posted by the FTB Bot so I am assuming it is the safest option. Feel free to enlighten me if you know what exactly this does to our computers. Cheers! 🙃

**Comment by Wallbreaker93** [comment] 2023-04-05 18:53
Since a lot of people seem to be riding around on the Firewalls, I can only say its not a problem caused by Windows Defender, DO NOT DISABLE IT, it doesnt change that the app keeps crashing

**Comment by MichaelHillcox** [comment] 2023-06-22 20:59
Closing as it's almost definitely a firewall issue. If anyone is still having this, please let me know.

**Closed by MichaelHillcox** 2023-06-22 20:59 UTC
Labels: bug
