### ISSUE TITLE
[Bug (MacOS)] Minecraft.app crashes when launching modpack

### ISSUE THREAD

**Issue by rafasoares** [FTBTeam/FTB-App#386] opened 2021-01-15 02:57 UTC
**Operating System:**
OS: macOS Big Sur v11.1

**Installer Version:**
Installer: FTBA_macos_202101041428-54016a89dc-release

**App Version:**
App: 202101041428-54016a89dc-release

**UI Version:**
UI: 6f769022

**Log Files:**
FTB App log: https://pste.ch/zomohowahe
macOS crash report: https://gist.github.com/rafasoares/022d32f3d04e6d3de541ff85b6ab05d0#file-macos-crash-report

** Debug Code: **
FTB-DBGOGEHIYOGIW

**Describe the bug**
Same bug as #160  

When launching a modpack via the FTB App, Minecraft.app crashes.

I have deleted the FTB App from my system (and the Application Support directory) and re-downloaded from the website, with the same results.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the Mac app
2. Mount the .dmg
2. Copy the app to the Applications folder
3. Run it (need to Ctrl+Click to run, since the app isn't signed)
4. Install a modpack (in this instance, FTB Presents Direwolf20 1.16 v1.3.1)
5. Try to play the modpack

**Expected behaviour**
The Minecraft.app launcher should open with the modpack profile, so I can play the game.

**Additional context**
 If I open the FTB App via the command line `/Applications/FTBApp.app/Contents/MacOS/JavaApplicationStub`, it works (as presented as a workaround in the original issue).

Strangely, the logs say `Failed to list directory. /Users/rafasoares/Library/Application Support/.ftba/instances
java.nio.file.NoSuchFileException: /Users/rafasoares/Library/Application Support/.ftba/instances`, but I have verified that the directory does, in fact, exist and it populated with the instance.

**Comment by Quetzi** [comment] 2021-02-02 12:03
Duplicate of #160 going to close here so that the bug is tracked in one place

**Closed by Quetzi** 2021-02-02 12:03 UTC
Labels: os/macos

**Comment by rafasoares** [comment] 2021-02-03 17:17
> Duplicate of #160 going to close here so that the bug is tracked in one place

I only opened a new issue bc I was told to after that issue was closed... 😅
