### ISSUE TITLE
Can't activate Cloud Storage even with paid MineTogether account

### ISSUE THREAD

**Issue by shank3001** [FTBTeam/FTB-App#857] opened 2023-02-12 07:57 UTC
### What Operating System

Windows 11

### Debug Code

FTB-DBGXAZUJEFUSA

### Describe the bug

I can't activate cloud storage, even though I have a paid MineTogether account

### Steps to reproduce

1. Go to settings of a modpack
2. Scroll down to Cloud save uploads
3. See that it is greyed out

### Expected behaviour

I should be able to activate the slider next to the Cloud Save option.

### Screenshots

![Screenshot 2023-02-11 235343](https://user-images.githubusercontent.com/10300791/218299548-3d7bbb0f-944f-4bfc-a5b7-9cb62d60b5cf.png)
![Screenshot 2023-02-11 235415](https://user-images.githubusercontent.com/10300791/218299549-8ff6aced-d467-431d-ae97-cff704b9380f.png)
![Screenshot 2023-02-11 235518](https://user-images.githubusercontent.com/10300791/218299550-17f234df-8c35-42d0-a4b8-90eb63f8f45b.png)
![Screenshot 2023-02-11 235654](https://user-images.githubusercontent.com/10300791/218299599-284014cd-45e9-47e0-af23-61422b8a525d.png)

**Comment by manmaed** [comment] 2023-02-13 21:16
Duplicate of #465 click to see more info

**Closed by manmaed** 2023-02-13 21:16 UTC
Labels: bug

**Comment by shank3001** [comment] 2023-02-15 08:33
Why was this closed when it is still an issue and the referencing bug was closed?
