### ISSUE TITLE
[Bug] cant get any pack to launch on linux

### ISSUE THREAD

**Issue by ANTBR14** [FTBTeam/FTB-App#88] opened 2020-04-12 01:04 UTC
**Operating System:**
OS: ubuntu 18.04. lts

**Installer Version:**
Installer: n/a

**App Version:**
App: 1.0.6

**UI Version:**
UI: c84af858

**Log Files:**
https://pste.ch/isibonisep

**Describe the bug**
all the packs download fine but when i try to launch from the mc launcher it crashes.

**To Reproduce**

**Expected behaviour**
the game to launch

**Comment by Cloudhunter** [comment] 2020-04-12 05:34
Can you please upload the Launcher logs from the Settings page?

**Comment by CH-Paul-T** [comment] 2020-04-12 08:41
I've read your log.

I think for some reason initially, the CDN was returning you an old/bad/cached 404 of some kind for that Forge version.

Now it appears to be downloading it, but it's still corrupted somehow as it is unable to get the json file out of the forge jar which it needs.

https://apps.modpacks.ch/versions/net/minecraftforge/forge/1.12.2-14.23.5.2846/forge-1.12.2-14.23.5.2846-universal.jar

Fancy downloading the above file and adding it here or telling us what you get when visiting the URL so we can figure out exactly what is going on? (File is fine for me)

I will look at the Forge logic myself these coming weeks and add the same checks I wrote for the actual mod jars etc to ensure this cannot happen in future.

**Comment by oworinge** [comment] 2020-04-16 13:18
Hi I'm not the original bug reporter but I'm experiencing the same bug, also on Ubuntu 18.04 but app version 1.0.8 now. The Minecraft launcher opens fine but when trying to launch any pack it crashes instantly.
From my logs however https://pste.ch/awetelefun which is just opening the launcher, installing the pack and attempting to launch it, the forge file does seem to be completely fine.

I also attempted to find if a log file was created in the minecraft instance but there is none there

**Comment by DutchessNicole** [comment] 2020-04-16 20:10
Chiming in on Linux Mint 19.3 (Ubuntu 18.04 based) with the exact same issue. I cannot find any log files to attach but the FTBApp works fine and starts the MC launcher, and when I hit the Play button on that I immediately get the "an unexpected issue occurred" window.

**Comment by oworinge** [comment] 2020-04-16 22:22
Okay I also did some digging and did find a log file for the launcher crash but it wasn't taken over into the instances folder and initially crashed my notepad program as line 15 was 1.4 million characters long. It was under FTBA/bin/launcher_log.txt and I've pasted the log with some bits removed: https://pste.ch/wovavagixu but its not really a FTBApp log so it might not be too useful

**Comment by DutchessNicole** [comment] 2020-04-22 08:19
I have tailed the last 1000 lines from the launcher.log again and they are visible [here](https://pastebin.com/36FYbqT7).
I see a lot of checksum failures like 

`Apr 16, 2020 9:50:24 PM net.creeperhost.creeperlauncher.CreeperLogger warning
WARNING: CarpentersBlocksCachedResources.zip size expected does not match remote file size. File size updated.
Apr 16, 2020 9:50:24 PM net.creeperhost.creeperlauncher.CreeperLogger warning
WARNING: CarpentersBlocksCachedResources.zip's SHA1 checksum failed.`

Could this be related to the crash?

**Comment by starlingfire** [comment] 2020-05-15 14:14
@DutchessNicole @oworinge, can you check something by perform the following steps:

1. Close Minecraft launcher
2. Close FTB launcher
3. Reopen FTB launcher and confirm there are no leading spaces to your java arguments
4. Launch the the Minecraft launcher from the FTB app
5. View the java arguments within the Minecraft launcher: are there two spaces between the `-Xmx` argument and the following argument? 

This is what I'm experiencing. The FTB launcher is generating an extra space between the `-Xmx` argument and `-XX:+UseG1GC`which is throwing errors. 

Even after confirming there are no leading spaces in my java arguments in the FTB launcher, it is inserting one into `launcher_profiles.json`. So each time I launch the Minecraft launcher, I have to  first go to my installation and delete the extra space, save, then I can launch the game. Alternatively, you can set the immutable flag (`sudo chattr +i launcher_profiles.json`) on the file so that the FTB app can't change it, but then you have to log in each time.

**Comment by DutchessNicole** [comment] 2020-05-15 21:25
Uhh I tried the steps you provided but I must be missing the debug step because I get no output at all when I start the launcher.
After opening and closing both the launcher and minecraft itself I start the FTBApp from the cli:
```
nicole@MintyNicole ~/FTBA $ ./FTBApp
```
No further output is generated at this time.
I don't have any custom java arguments configured, only the memory allocation has been changed.
The Custom Arguments box is therefore empty.
Saving and running the Minecraft brings up the regular MC launcher as usual.
HItting "Play" causes the launcher to disappear and immediately reappear with the error message as before.

No output was generated in the terminal during all this.

Looking in the launcher_profiles.json it doesn't seem to be the same issue: for this profile (the only one I have for now) the section reads
```
      "javaArgs" : "-Xmx10388M",
      "lastUsed" : "2020-05-15T21:21:26.863Z",
      "lastVersionId" : "1.7.10-forge1.7.10-10.13.4.1614",
      "name" : "FTB Infinity Evolved 1.7",
      "resolution" : {
        "height" : 1080,
        "width" : 1920
      },
      "type" : "custom"
    },
```
I have grepped for the Xmx  and UseG1GC strings inside the FTBApp directory but there's no mention of either.

How did you find these?

**Comment by starlingfire** [comment] 2020-05-19 14:13
@DutchessNicole, it seems your issue isn't the same as mine, sorry. I just reread your previous comment about checksum failures, so it doesn't look like it's even getting to the point where mine was failing.

**Comment by DutchessNicole** [comment] 2020-07-16 08:18
Just as a reminder: this is still a problem.
On a fresh Linux Mint 20 install with a current (today) download of the launcher, the minecraft client still crashes with the unexpected error message.

`[Info: 2020-07-16 08:15:59.717398369: ClientStarter.cpp(811)] Java argument:-Xmx4096M
[Info: 2020-07-16 08:15:59.717417669: ClientStarter.cpp(834)] Starting game in folder .../instances/547e7c39-2d2f-4ac2-b940-8ddd2d791951 using java executable 
//.../java
[Info: 2020-07-16 08:15:59.717446099: Process_Linux.cpp(20)] Creating process /usr/lib/jvm/java-11-openjdk-amd64/bin/java
[Info: 2020-07-16 08:15:59.717581059: NetQueue.cpp(239)] NetQueue: Initiating shutdown.
[Info: 2020-07-16 08:15:59.717617969: NetQueue.cpp(245)] NetQueue: Waiting for worker thread to finish...
[Info: 2020-07-16 08:15:59.720481611: NetQueue.cpp(658)] NetQueue: Worker thread shutting down.
[Info: 2020-07-16 08:15:59.720601632: NetQueue.cpp(248)] NetQueue: Done.
[Info: 2020-07-16 08:15:59.720670482: Process_Linux.cpp(115)] Starting process /usr/lib/jvm/java-11-openjdk-amd64/bin/java
[Info: 2020-07-16 08:15:59.723505084: root_window_gtk.cpp(221)] Close called, window: 0x25b4270
[Info: 2020-07-16 08:15:59.723538794: client_handler.cpp(625)] ClientHandler::NotifyBrowserClosing
[Info: 2020-07-16 08:15:59.780318354: GameCallbacks.cpp(158)] Game/game () Info Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loa
der.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader ar
e in module java.base of loader 'bootstrap')
[Info: 2020-07-16 08:15:59.780363384: GameCallbacks.cpp(158)] Game/game () Info at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
[Info: 2020-07-16 08:15:59.780373164: GameCallbacks.cpp(158)] Game/game () Info at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[Info: 2020-07-16 08:15:59.783691997: GameCallbacks.cpp(158)] Launcher/monitor (Process Monitor) Fatal Process crashed with exit code 1
[Info: 2020-07-16 08:15:59.784130957: GameController.cpp(480)] Game closed with id 1
`
This is some of the output provided

**Comment by starlingfire** [comment] 2020-07-17 11:10
@DutchessNicole  what version of java are you using?

`java -version`

**Comment by DutchessNicole** [comment] 2020-07-17 13:47
`|-- nicole@MintyNicole20:~ --|
$ java -version 
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
`

**Comment by starlingfire** [comment] 2020-07-17 15:48
@DutchessNicole, I think that's your issue. Forge still needs Java 8 to run. You should uninstall Java 11 and install 8, which you can do with

`apt-get install openjdk-8-jdk`

**Comment by DutchessNicole** [comment] 2020-07-19 19:34
Thank you for the information. I installed openjdk-jre8 as you suggested and added the following to the configuration within the **minecraft client itself for the modpack**:
Minecraft Launcher -> Edit installation -> More options -> Java executable = /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

With that, the launcher can successfully start up.
Unfortunately the minecraft launcher doesn't seem to actually save the value of the java executable, but that is not a FTBApp issue.

Thank you for your assistance! For me the issue is now closed

**Comment by starlingfire** [comment] 2020-07-19 20:24
@DutchessNicole glad it's sorted! Unless you need it for other things, I'd just uninstall the other versions of Java, then you *shouldn't* need to specify the binary. But who actually knows if that will stick...

**Comment by DutchessNicole** [comment] 2020-07-20 06:11
unfortunately i need the more recent version for some other software packages so I can't uninstall it, but this works for me so far :)

**Comment by Gaz492** [comment] 2021-01-14 22:50
If anyone is still having issues with the app please open a new issue.

**Closed by Gaz492** 2021-01-14 22:50 UTC
Labels: backend, bug
