### ISSUE TITLE
[Bug] Memory not allocating properly when using ftb app

### ISSUE THREAD

**Issue by nightowl85** [FTBTeam/FTB-App#108] opened 2020-04-17 18:52 UTC
I posted this one the ftb app page on the ftb discord but I was told to post it here: "ok so when i try to run modpacks using this app, it doesn't load. I figured out, by trying to load ftb revelation, that its limiting my memory to less than half a gb, which would explain why it couldn't load. But I don't understand why its doing this because I am allocating 4+ gb in the settings tab of the modpacks. I don't have this problem with modpacks in the technic launcher. Has anyone had this problem or has any clue how to fix it? I've tried reinstalling everything multiple times." 

No one else seems to have had this problem; not sure what it is or if it has something to do with my pc or settings, but I've looked around and can't seem to find anything that would fix i, and like I said modpacks on the technic launcher work fine so I think this could definitely be a bug with the ftb app somehow.

Thanks.

**Comment by Gaz492** [comment] 2020-10-21 17:03
Hi,

This issue should have been fixed in one of the latest versions of the app.

If the issue is still happening please open a new issue so we can track it.

**Closed by Gaz492** 2020-10-21 17:03 UTC
