### ISSUE TITLE
[Feature request] Allow external JDKs

### ISSUE THREAD

**Issue by enderger** [FTBTeam/FTB-App#644] opened 2022-07-27 01:14 UTC
**Is your feature request related to a problem? Please describe.**
As mentioned in Discord, several systems (in our case, NixOS) require JDKs linked against libraries in locations which differ from standard builds. Thus, to have any semblance of portibility (the whole point of Java abstracting over this in the first place), external JDKs must be addable by the user.

**Describe the solution you'd like**
The user, likely under some advanced settings menu, should be able to specify Java installs which take priority over their automatically installed counterparts.

**Describe alternatives you've considered**
Removing the Java installation system entirely, though that alienates users who can't install Java for a second time (as the launcher appears to depend on it already).

**Additional context**

**Comment by MichaelHillcox** [comment] 2022-07-27 15:42
Duplicate of #467 and it's been fixed in dev, being released today :+1:

**Closed by MichaelHillcox** 2022-07-27 15:42 UTC
