### ISSUE TITLE
[Bug]: App will not sign me in

### ISSUE THREAD

**Issue by Ramenbowljr** [FTBTeam/FTB-App#606] opened 2022-06-13 03:47 UTC
### What Operating System

Windows 10

### Debug Code

There is no code

### Describe the bug

It says that I have successfully logged in, yet on the app there is still no account signed in.  

### Steps to reproduce

There is nothing for me to click on. 

### Expected behaviour

N/A

### Screenshots

![FTB error](https://user-images.githubusercontent.com/107381569/173275659-ea342ab2-86d2-4e14-984e-d5261c311353.PNG)
![FTB error 2](https://user-images.githubusercontent.com/107381569/173275666-3dc344f9-2a87-4c5c-b4c0-7c8b64b7752d.PNG)

### Additional information

When I sign into my Microsoft account, the browser says successful login, yet when I go back into the app I am not signed in. It does not give me any kind of error message and I have tried uninstalling and reinstalling it did not fix it. I was signed in but I accidently signed out and now I cant get back in, 

### Information

- [X] I have provided as much information as possible

**Comment by caltex-glitch** [comment] 2022-06-13 03:51
FTB-DBGODUBISAPES

**Comment by caltex-glitch** [comment] 2022-06-13 03:51
> FTB-DBGODUBISAPES

this happen exactly the same for me

**Comment by MrTetas** [comment] 2022-06-13 03:53
FTB-DBGMUSESUCAJE
yeah same here i cant sign in

**Comment by Ramenbowljr** [comment] 2022-06-13 03:55
Its extremely frustrating because I was signed in and I signed out because the app was not launching a mod, and now I cant get back in.

**Comment by Azutte** [comment] 2022-06-13 03:57
I'm also having this issue. FTB-DBGUDEJUGUDOZ

**Comment by ripley5555** [comment] 2022-06-13 03:58
FTB-DBGDUFAQIBOVE

I have the exact same issue as well

**Comment by AnotherDBK** [comment] 2022-06-13 03:59
Same here WTF

**Comment by Kalebon** [comment] 2022-06-13 03:59
Same as well.

**Comment by AnotherDBK** [comment] 2022-06-13 04:00
FTB-DBGXARUFAJILO here is my code

**Comment by Kalebon** [comment] 2022-06-13 04:01
FTB-DBGGURISEPINA Is my code

**Comment by Piepaz01** [comment] 2022-06-13 04:01
FTB-DBGUSIXESINAN 

I have the same problem as well

**Comment by Ramenbowljr** [comment] 2022-06-13 04:02
I ain’t even getting a code which is the worst part

**Comment by AnotherDBK** [comment] 2022-06-13 04:04
I think their servers are down or something because it wont even let me verify on discord...

**Comment by Piepaz01** [comment] 2022-06-13 04:04
Im not getting discord verification either

**Comment by AnotherDBK** [comment] 2022-06-13 04:05
This is pissing me off either way

**Comment by SDSDUTCH** [comment] 2022-06-13 04:06
> Im not getting discord verification either

they must be because im haveing the same problem for signing into the FTB launcher and discord not verifying

**Comment by MrTetas** [comment] 2022-06-13 04:13
> I think their servers are down or something because it wont even let me verify on discord...

yeah sameee
this is so annoying

**Comment by lutzenfamily** [comment] 2022-06-13 04:13
SAME Cannot get logged in. Seems everyone is having this issue.

**Comment by PatrickEngelbert2** [comment] 2022-06-13 04:14
Same issue for me. I'm guessing this is an API issue.

**Comment by wimos-ai** [comment] 2022-06-13 04:17
Same issue. I have tried reinstalling, clearing caches, reinstalling overwolf, and reinstalling everything.

**Comment by AnotherDBK** [comment] 2022-06-13 04:20
Yep ive tried unistalling and everything aswell...

**Comment by Uneed2P** [comment] 2022-06-13 04:22
Okay I thought the issue was just happening to me. I just cat the same moment had a mod pack mess up and cause an issue.

**Comment by wimos-ai** [comment] 2022-06-13 04:23
Can confirm that removing and re-adding FTB from Apps and services that can access your data fixed the issue for me.

**Comment by AnotherDBK** [comment] 2022-06-13 04:24
> Can confirm that removing and re-adding FTB from Apps and services that can access your data fixed the issue for me.
 where can i find that page i was looking for a solid 4 minutes lol

**Comment by TheGoldenProof** [comment] 2022-06-13 04:25
It seems like they fixed it. I completely closed FTB App and Overwolf, and when I relaunced it, it loaded for a bit and signing in worked.

**Comment by Uneed2P** [comment] 2022-06-13 04:29
> Can confirm that removing and re-adding FTB from Apps and services that can access your data fixed the issue for me.

yes works now!

**Comment by Kalebon** [comment] 2022-06-13 04:31
same did a reinstall and it is working now.

**Comment by SeRRedz** [comment] 2022-06-17 16:36
FTB-DBGXILEVEREYA

**Comment by ThatCoffeeGuy** [comment] 2022-06-24 08:27
I believe this was because of the cloudflare outage that would kill some msauth servers.

**Comment by MichaelHillcox** [comment] 2022-07-23 10:42
Hi, sorry for the slow reply, this error was caused by one the Microsoft authentication services being down. This has been fixed now on their end. There is a different issue that was causing our service to fatally error because of this and this has now been resolved :+1: 

We'll be releasing an update in the coming days that'll address some more authentication issues like this. For now, because this specific issue is resolved, I'm going to close this issue.

**Closed by MichaelHillcox** 2022-07-23 10:42 UTC
Labels: bug
