### ISSUE TITLE
[Bug]: Cant download most packs and cant run the few I can

### ISSUE THREAD

**Issue by SaltyVenator** [FTBTeam/FTB-App#538] opened 2022-04-30 05:32 UTC
### What Operating System

Windows 10

### App Version

202204211116-ac2e189d70-release

### UI Version

ac2e189d70

### Log Files

https://pste.ch/fagacahoro

### Debug Code

FTB-DBGSUWEJUCIPO

### Describe the bug

Cant download most packs

### Steps to reproduce

1. Open app ( still doesn't work with admin access)
2. Try to download modpack ( mosty oceanblock)
3. so far only stoneblock 2 will download but cant run it 

### Expected behaviour

I don't have requisite programs or apps?

### Screenshots

![help](https://user-images.githubusercontent.com/104655893/166092775-8e241156-b091-4600-a2f6-3cb9ea8bf310.png)

### Information

- [X] I have provided as much information as possible

**Comment by pherr80** [comment] 2022-05-07 00:21
I am having the same exact issue as well

**Comment by foghagymatyi** [comment] 2022-05-17 14:56
I am having the same issue any way we can fix this?

**Comment by joakime** [comment] 2022-05-21 00:25
It happened to me as well, turns out FTBApp doesn't sanitize filenames on windows.
Opened issue #558

The modpack had a file with name containing a `:` and caused an error attempting to manipulate it.

**Comment by Elpximso** [comment] 2022-05-21 22:42
Having the same problem

**Comment by CoryNB** [comment] 2022-05-23 21:19
reinstall a clean version with the latest system. make sure you have curseforge and legacy classic ftb launcher before doing it. you might also want mutimc.

**Comment by joakime** [comment] 2022-05-23 21:31
What's "mutimc"?  Do you mean "MultiMC"?
MultiMC cannot install curse or forge packs anymore due to curse API changes.
(see https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc )

**Comment by CoryNB** [comment] 2022-05-23 21:34
I usually leave it lying around, because it could also draw code from it directly if needed. It served for more than 1 mod-pack instance running at once.

**Comment by MichaelHillcox** [comment] 2022-07-24 13:21
`Caused by: java.net.UnknownHostException: No such host is known (api.adoptium.net)` may be the original issue

**Comment by joakime** [comment] 2022-07-24 20:06
@MichaelHillcox on Windows, we still cannot download any pack with the `:` (colon) character in it's tltle from curseforge.
This is because the FTBApp will attempt to create a file called `<pack-title>-<version>-overrides.zip` which is the name of the pack title as-is, no sanitization.
Obviously windows rejects this filename as it has a forbidden character `:` (colon)

An example curseforge project which always (100% of the time) fail on FTPApp on Windows.
https://www.curseforge.com/minecraft/modpacks/valhelsia-enhanced-vanilla

_Works on FTPApp on Linux btw._

**Comment by MichaelHillcox** [comment] 2022-07-24 20:16
Awesome, thanks for the info, this should be a pretty quick fix, not sure if @ThePaul-T can make this change in the api?

**Comment by joakime** [comment] 2022-07-24 23:28
> Awesome, thanks for the info, this should be a pretty quick fix, not sure if @ThePaul-T can make this change in the api?

There's a speculative PR open at #560 already for that.

**Comment by covers1624** [comment] 2022-07-27 10:55
This has been fixed in dev.

**Closed by covers1624** 2022-07-27 10:55 UTC
Labels: bug, subprocess
