### ISSUE TITLE
An error occurred whilst launching

### ISSUE THREAD

**Issue by mrgrumbly** [FTBTeam/FTB-App#861] opened 2023-02-16 22:50 UTC
### What Operating System

Windows 10

### Debug Code

FTB-DBGYOVEVAQOMI

### Describe the bug

I can't get any of the modpacks to open

### Steps to reproduce

1. open ftb app
2. click play on modpack
3. An error occurred whilst launching because net.creeperhost.creeperlauncher.install.tasks.DownloadFailedException: Download failed.
Tried URL: 'https://apps.modpacks.ch/meta.json' 6 times.

### Expected behaviour

I expected the modpack to open like normal. 

### Screenshots

![FTB App 2_16_2023 3_48_09 PM](https://user-images.githubusercontent.com/125613739/219504513-b31b8739-a768-4a40-8ba5-4ee629b3d6b2.png)

### Additional information

this is all over my head. I can't think of anything that changed.

**Comment by mrgrumbly** [comment] 2023-02-17 05:17
I've tried installing other modpacks and I get the Fatal Exception whilst installing error. This is very baffling. I even tried to uninstall and reinstall the FTB app and it opened the modpack and I even played for a while. Then I closed the modpack and tried to open it again and I am back to the same errors I listed above. I am officially lost.

**Comment by BinaryVigilante** [comment] 2023-02-17 20:50
I can confirm this error, I'm getting the same one. I'm on Arch Linux. I took this from the FTB App log file:

```
[21:43:34] [ForkJoinPool.commonPool-worker-2/ERROR] [net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler]: Failed to launch instance.
net.creeperhost.creeperlauncher.pack.InstanceLaunchException: Failed to prepare instance 'FTB Legend of the Eyes'(1045a4d2-eab8-464b-b83b-2631352cd6aa).
        at net.creeperhost.creeperlauncher.pack.InstanceLauncher.prepareProcess(InstanceLauncher.java:479) ~[launcher-202302161806-1c8edb0091-release-all.jar:?]
        at net.creeperhost.creeperlauncher.pack.InstanceLauncher.launch(InstanceLauncher.java:151) ~[launcher-202302161806-1c8edb0091-release-all.jar:?]
        at net.creeperhost.creeperlauncher.pack.LocalInstance.play(LocalInstance.java:398) ~[launcher-202302161806-1c8edb0091-release-all.jar:?]
        at net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler.lambda$handle$0(LaunchInstanceHandler.java:58) ~[launcher-202302161806-1c8edb0091-release-all.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: net.creeperhost.creeperlauncher.install.tasks.DownloadFailedException: Download failed.
Tried URL: 'https://apps.modpacks.ch/meta.json' 6 times.
```

**Comment by SpeedSlider** [comment] 2023-02-18 00:52
I have all the same issues on windows 10 machine, but I don't get a debug code when I run the debug tool I get all green successful, but still can't do anyting I even deleted my login and readded the Microsoft Minecraft account. I currently have four FTB packs and Admin a streamers server for Stoneblock3 which I can no longer login to since it got goofed up trying to update from 1.5.0 to 1.6.1. I don't want to uninstall and reinstall the app as I have four modpacks with single player worlds that I would need to backup and readd.

**Comment by adrimax11** [comment] 2023-02-18 15:54
The problem occurs when you have Kaspersky antivirus, close it and try again. It has worked for me doing that

**Comment by SpeedSlider** [comment] 2023-02-18 18:58
So the real question is why now as I have had Kaspersky the hole time I have used the FTB launcher?

**Comment by SpeedSlider** [comment] 2023-02-18 19:26
Also, you apparently have to close Kaspersky each time you restart the program, or the computer, etc. so not a permanent solution. I was able to download and play the one pack after windows defender needed an exception, but that exception appears to only work per instance you have to do it for every instance or every time you play.

**Comment by KnottaHooker** [comment] 2023-02-20 15:45
I'm having the same issue and have Kaspersky. This only started happening to me on Friday after the latest Windows update. It occurs with every single modpack I either already have or try to download.

**Comment by SpeedSlider** [comment] 2023-02-21 19:29
The setting is to use HTTPS (s=secure) versus plain text communication which implies the FTB app sends everything to and from you computer in plain text format which is unsecure. All my other minecraft launchers, including other modpacks, work just fine without any changes which implies they all are secure.

**Comment by gessmine** [comment] 2023-02-22 14:28
Hello, hope that sharing this will help others.  I experienced the exact same issue that mrgrumbly shared in an image.  I was unable to run any of the instances and received the same error for all of them.  I am on a MacBook M1 Max with Ventura 13.2.1.  The Anti Virus I am running is Bitdefender.  I encountered the issue after the FTB Launcher updated last night.  After 30 minutes of messing around with settings and looking at logs I decided to reboot.  That fixed the issue.  The FTB Launcher is now working as expected.  If there are any logs or other information I can share that would help, let me know.  Thanks.

**Comment by christmasjoke** [comment] 2023-05-31 08:34
i dont have any antivirus and i get the same issue with all modpacks

**Comment by MichaelHillcox** [comment] 2023-06-22 20:59
Closing as it's a network issue. If this is still happening, please let me know.

**Closed by MichaelHillcox** 2023-06-22 20:59 UTC
Labels: bug

**Comment by juaps** [comment] 2025-04-04 04:02
I have the same error, im on Mac, so there is NULL antivirus here, the same problem with FTB
