### ISSUE TITLE
Multiple users cannot launch the game after Omnia 1.3.0 update Issue 2 of 2

### ISSUE THREAD

**Issue by chadbob** [FTBTeam/FTB-App#133] opened 2020-05-08 00:40 UTC
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: Omnia 1.3.0

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
Put links to your logs here
https://pste.ch/nuxidukoxa

**Describe the bug**
Another user has an issue when trying to install the Omnia 1.3.0 update he gets an error and the update never finishes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to FTB Launcher
2. Click on Omnia then Versions
3. Scroll down to Click Install and/or Update 1.3.0

**Expected behaviour**
I expect the modpack to update

**Screenshots**
![image](https://user-images.githubusercontent.com/64994707/81357811-a543b100-90a2-11ea-8ede-b195ac1363c3.png)

**Additional context**

**Comment by Rushmead** [comment] 2020-05-19 12:59
This was caused by the Forge installer not being where it should have been on the backend. This was fixed within a matter of minutes of the pack being released and should now be resolved.

**Closed** 2020-05-22 11:49 UTC
