### ISSUE TITLE
[Feature request] Mod listings for mod packs.

### ISSUE THREAD

**Issue by VasVadum** [FTBTeam/FTB-App#427] opened 2021-08-04 04:17 UTC
**Describe the solution you'd like**
I would like to see a mod tab for each mod pack in the interface, that would show me what mods are in the mod pack before I subscribe to it. Like on the site where you can see all the mods inside a mod pack.

**Additional context**
I like to know what I'm getting before I get it, so I'd like to know exactly what mods are in something, before I download it.

**Comment by MichaelHillcox** [comment] 2021-08-11 10:19
duplicate of https://github.com/FTBTeam/FTB-App-Feedback/issues/20 thanks for the report

**Closed by MichaelHillcox** 2021-08-11 10:19 UTC
